dump cmake logs when failed

diff --git a/.github/workflows/github_actions.yml b/.github/workflows/github_actions.yml
--- a/.github/workflows/github_actions.yml
+++ b/.github/workflows/github_actions.yml
@@ -157,5 +157,13 @@ jobs:
         run: |
           pwd
           ls
-          find . -name config.log -exec cat {} ";"
-          cat ./test-suite.log
+          find . -name config.log -exec cat {} ";" || true
+          cat ./test-suite.log || true
+          echo '***** CMakeOutput.log *****'
+          find . -name CMakeOutput.log -exec cat {} ";" || true
+          echo '***** CMakeError.log ******'
+          find . -name CMakeError.log  -exec cat {} ";" || true
+          echo '***********'
+          cat /Users/runner/work/ga/ga/build/CMakeFiles/CMakeOutput.log || true
+          echo '***********'
+          cat /Users/runner/work/ga/ga/build/CMakeFiles/CMakeError.log || true
